tkrajina/gpxpy

- .travis.yml
- test.py
Because `pip install lxml` involves slow building lxml from source, use lxml wheels where available.
Use unittest2 for Python 2.6.
Run tests on Travis CI with coverage, and report coverage to Coveralls. Coverage is a good 85%. This gives reports like [this](https://travis-ci.org/hugovk/gpxpy/builds/116115946) and [this](https://coveralls.io/builds/5421207).
TODO: Ideally before merge, please can you enable these free services:
> Run unit tests with coverage on Travis CI

- gpxpy/__init__.py
- gpxpy/parser.py
Change allows one to force a gpx version to be used. Useful for gpx files which use extensions but don't set the version attribute of the gpx node, or don't set it to "1.1".
The main use of this is to let you call the parse function like so:
gpx = gpxpy.parse(gpx_file, version = "1.1")
> Allow forcing version

- test.py
- test_files/unicode3.gpx
Added tests 'test_unicode_bom' and 'test_force_version'.
The 'unicode3.gpx' file has a UTF-8 byte order marker. This probably won't be displayed in many text editors, but it is there. It also has no attributes in the gpx node, but does have an extensions node.
A potential issue is that the force version test will fail if the parser doesn't handle UTF-8 files with byte order markers. This is because I used the same file for the byte order marker test as well as the force version test.
I'm not too familiar with this testing system. I hope I've done it right. I wrote these because the coverage checker complained about reduced coverage in my UTF-8 BOM support pull request.
p.s. I noticed that there are two 'test_unicode' functions defined - one on line 315, the other on 1616. I don't know if …
> Add test for Force Version change and test for files with UTF-8 BOM

- gpxpy/gpxfield.py
- test.py
passed unit tests on python2.7 (I don't have 3 currently installed)
> remove timezone part from date string

- gpxinfo
For poor folks in countries not yet converted to metric, miles and feet are a useful summary option. The PR adds a -m option to select miles/feet instead of km/m. I have attempted to follow the style of the existing code. I also put the commented logging setting in with -d.
No offense taken if you prefer not to complicate the code with this extra feature.
> Add -m option for miles/feet

- gpxpy/parser.py
Using `exc_info=True` instead of `log.exception(e)`. 
For https://github.com/tkrajina/gpxpy/issues/111
> exception as debug level

- .travis.yml
- README.md
- test.py
Python 2.6 and 3.2-3.3 are EOL and no longer receiving security updates (or any updates) from the core Python team.
They're also little used.
Here's the pip installs for gpxpy from PyPI for July 2018:
| python_version | percent | download_count |
| -------------- | ------: | -------------: |
| 2.7            |  82.58% |          3,561 |
| 3.6            |  12.73% |            549 |
| 3.5            |   3.43% |            148 |
| 3.7            |   1.00% |             43 |
| 3.4            |   0.26% |             11 |
| Total          |         |          4,312 |
Source: `pypinfo --start-date 2018-07-01 --end-date 2018-07-31 --percent --markdown gpxpy pyversion`
Python 2.6 has already been dropped (#105), this removes some extra code for that.
It also removes 3.2 and 3.3 support which …
> Drop support for EOL Python

- CHANGELOG.md
- gpxpy/gpx.py
- gpxpy/gpxfield.py
- gpxpy/parser.py
- setup.py
- test.py
- test_files/custom_schema_locations.gpx
- test_files/default_schema_locations.gpx
Added the ability to set schemaLocation explicitly in a GPX object. This is done to support custom schemas for extensions when generating xml (for example, http://developer.garmin.com/downloads/connect-api/sample_file.gpx)
```
gpx = gpxpy.GPX()
gpx.schema_locations = [
'http://www.topografix.com/GPX/1/1',
'http://www.topografix.com/GPX/1/1/gpx.xsd',
'http://www.garmin.com/xmlschemas/GpxExtensions/v3',
'http://www.garmin.com/xmlschemas/GpxExtensionsv3.xsd',
]
```
> Option to override xsi:schemaLocation for custom extensions schema

- setup.py
Some handy updates to setup.py:
* Update Trove classifiers so the supported versions are clear on PyPI https://pypi.org/project/gpxpy/
* Use `setuptools` rather than `distutils` for:
* Add `python_requires`, so pip knows which version of this package to install for people's installed Python version
* Add the README.md contents as `long_description` so https://pypi.org/project/gpxpy/ will show the README instead of "The author of this package has not provided a project description"
For these, make sure you have `pip install -U setuptools twine` and use `twine` for upload.
See:
* https://dustingram.com/articles/2018/03/16/markdown-descriptions-on-pypi
* https://github.com/di/markdown-description-example
> Setup.py: update classifiers, add python_requires and long_description

- .travis.yml
- setup.py
A little workaround is needed for 3.7 on Travis, see https://github.com/travis-ci/travis-ci/issues/9815.
> Add Python 3.7 classifier and test on CI

- gpxpy/__init__.py
- setup.py
This change adds `gpxpy.__version__` into the package by moving the version string into `__init__.py` and then importing/reading that value from setup.py.
Tests ran cleanly and coverage remained unchanged.
```
Ran 124 tests in 4.021s
OK (skipped=1)
$
$ coverage report
Name                Stmts   Miss  Cover
---------------------------------------
gpxpy/__init__.py       5      0   100%
gpxpy/geo.py          203     21    90%
gpxpy/gpx.py         1219    184    85%
gpxpy/gpxfield.py     336     35    90%
gpxpy/gpxxml.py        49     16    67%
gpxpy/parser.py        54      7    87%
gpxpy/utils.py         55     21    62%
---------------------------------------
TOTAL                1921    284    85%
```
This addresses enhancement/issue #116.
> add package __version__ (fixes #116)

- gpxpy/__init__.py
- gpxpy/geo.py
- gpxpy/gpx.py
- gpxpy/gpxfield.py
- gpxpy/gpxxml.py
- gpxpy/parser.py
- gpxpy/utils.py
- setup.py
- test.py
- xsd/pretty_print_schemas.py
Update `python_requires` to tell pip to only install on Python 3.6+.
Also upgrade Python syntax using https://github.com/asottile/pyupgrade, to take advantage of features of Python 3.6.
> Update python_requires and upgrade Python syntax

- gpxpy/geo.py
- gpxpy/gpx.py
- test.py
This pull request implements the course computation between two points and closes #155.
As @christianhauff mentioned in #155, the course attribute was removed in GPX v1.1
This parameter is extremely useful when we need to visualize vehicle movement on a map (e.g. when we replay the movement logs in vehicle tracking systems).
A vehicle icon on map typically has two dimensions, so to rotate it correctly in each point we need to know its course/heading/bearing/azimuth* to a next point.
_*In most cases for the land-based vehicles these definitions are typically identical_
_Original version by WolfgangW; modified and converted to SVG by ctree. [CC BY-SA (https://creativecommons.org/licenses/by-sa/4.0)]_
To compute instantaneous course between two points, a user can choose between …
> Course computation

- test.py
> Use list instead of getchildren for Python 3.9 compatibility.

- gpxpy/gpx.py
- test.py
The original code of get_nearest_location(location) has the property that if 'location' is a point on the track, the point after 'location' on the track is returned (for that case 'not distance' is True because distance is 0.0).
There is a version that only adjusts for this behavior in the middle commit. 
I consider the version using min(..,key=lambda ..) even more readable.
One could consider this a hotfix, so perhaps it should be a pull request on master.  If you prefer this, I can prepare such a pull request. (I'll have to do it from a different fork because this one has the full merge of dev...)
> bugfix and simpler code

- .travis.yml
Replace `3.9-dev` with `3.9`.
Would you actually consider moving to GitHub Actions CI?
> Add Python 3.9 to .travis.yml

- gpxpy/utils.py
- test.py
As described in issue #229 an error happens if a float of size 10^16 or larger with at least one trailing zero is used.
This pull request fixed this issue and provides a test.
> Fix bug #229

- CONTRIBUTING.md
- README.md
- gpxpy/gpx.py
There are small typos in:
- CONTRIBUTING.md
- README.md
- gpxpy/gpx.py
Fixes:
- Should read `containing` rather than `containint`.
- Should read `specified` rather than `specificed`.
- Should read `issue` rather than `inssue`.
- Should read `access` rather than `acess`.
Closes #235
> docs: fix a few simple typos

- README.md
- examples/extension_write_example.py
- examples/waypoints_example.py
- gpxinfo
- gpxpy/gpx.py
- gpxpy/gpxfield.py
- gpxpy/parser.py
- gpxpy/utils.py
- test.py
- xsd/pretty_print_schemas.py
1. Use Python3 defaults, such as source code file encoding or reading mode for opened file
2. Log entries should not be pre-formatted, so use `log.info('hello %s', 'world')` instead of `log.info('hello %s' % 'world)`
3. Use f-strings. All updates within one commit, but all changes are self-contained within their methods/blocks and no public interfaces have been affected
> Modernize code to Python 3.6+

- gpxpy/gpxfield.py
- gpxpy/utils.py
- test.py
Issue #225
To reduce the processing time and to make the code simple, .isoformat() is used instead of strftime.
TZ format is changed from '+/-HHMM' to '+/-HH:MM'.  Both of the formats are allowed in the standard.
> Avoid using strftime in format_time

- makefile
Fixes https://github.com/tkrajina/gpxpy/issues/237.
Currently, gpxpy is distributed on PyPI only as a sdist:
* https://pypi.org/project/gpxpy/1.5.0/#files
Please could you also distribute a wheel? It makes installation faster. More info: 
* https://pythonwheels.com/
This PR updates the `makefile` to create both an sdist and wheel using https://github.com/pypa/build, and upload both.
This solves another problem too, calling `setup.py` directly is deprecated by setuptools:
* https://blog.ganssle.io/articles/2021/10/setup-py-deprecated.html
> Use python-build to also make wheels
